// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "datatbl.h"

// Dispatch interfaces referenced by this interface
#include "font.h"
#include "dtcurcell.h"
#include "dtrowset.h"
#include "dtcolumnset.h"
#include "DTCellSet.h"

/////////////////////////////////////////////////////////////////////////////
// CDatatbl

IMPLEMENT_DYNCREATE(CDatatbl, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CDatatbl properties

unsigned long CDatatbl::GetGridLineColor()
{
	unsigned long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CDatatbl::SetGridLineColor(unsigned long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

BOOL CDatatbl::GetAllowPaintCellEvent()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CDatatbl::SetAllowPaintCellEvent(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

BOOL CDatatbl::GetVertGridLines()
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

void CDatatbl::SetVertGridLines(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

long CDatatbl::GetVertScrollBar()
{
	long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CDatatbl::SetVertScrollBar(long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

BOOL CDatatbl::GetVertSplitPane()
{
	BOOL result;
	GetProperty(0x5, VT_BOOL, (void*)&result);
	return result;
}

void CDatatbl::SetVertSplitPane(BOOL propVal)
{
	SetProperty(0x5, VT_BOOL, propVal);
}

BOOL CDatatbl::GetHorzSplitPane()
{
	BOOL result;
	GetProperty(0x6, VT_BOOL, (void*)&result);
	return result;
}

void CDatatbl::SetHorzSplitPane(BOOL propVal)
{
	SetProperty(0x6, VT_BOOL, propVal);
}

unsigned long CDatatbl::GetSelBackColor()
{
	unsigned long result;
	GetProperty(0x7, VT_I4, (void*)&result);
	return result;
}

void CDatatbl::SetSelBackColor(unsigned long propVal)
{
	SetProperty(0x7, VT_I4, propVal);
}

long CDatatbl::GetHorzScrollBar()
{
	long result;
	GetProperty(0x8, VT_I4, (void*)&result);
	return result;
}

void CDatatbl::SetHorzScrollBar(long propVal)
{
	SetProperty(0x8, VT_I4, propVal);
}

BOOL CDatatbl::GetHorzGridLines()
{
	BOOL result;
	GetProperty(0x9, VT_BOOL, (void*)&result);
	return result;
}

void CDatatbl::SetHorzGridLines(BOOL propVal)
{
	SetProperty(0x9, VT_BOOL, propVal);
}

unsigned long CDatatbl::GetSelForeColor()
{
	unsigned long result;
	GetProperty(0xa, VT_I4, (void*)&result);
	return result;
}

void CDatatbl::SetSelForeColor(unsigned long propVal)
{
	SetProperty(0xa, VT_I4, propVal);
}

OLE_COLOR CDatatbl::GetBackColor()
{
	OLE_COLOR result;
	GetProperty(DISPID_BACKCOLOR, VT_I4, (void*)&result);
	return result;
}

void CDatatbl::SetBackColor(OLE_COLOR propVal)
{
	SetProperty(DISPID_BACKCOLOR, VT_I4, propVal);
}

BOOL CDatatbl::GetEnabled()
{
	BOOL result;
	GetProperty(DISPID_ENABLED, VT_BOOL, (void*)&result);
	return result;
}

void CDatatbl::SetEnabled(BOOL propVal)
{
	SetProperty(DISPID_ENABLED, VT_BOOL, propVal);
}

COleFont CDatatbl::GetFont()
{
	LPDISPATCH pDispatch;
	GetProperty(DISPID_FONT, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CDatatbl::SetFont(LPDISPATCH propVal)
{
	SetProperty(DISPID_FONT, VT_DISPATCH, propVal);
}

OLE_COLOR CDatatbl::GetForeColor()
{
	OLE_COLOR result;
	GetProperty(DISPID_FORECOLOR, VT_I4, (void*)&result);
	return result;
}

void CDatatbl::SetForeColor(OLE_COLOR propVal)
{
	SetProperty(DISPID_FORECOLOR, VT_I4, propVal);
}

OLE_HANDLE CDatatbl::GetHWnd()
{
	OLE_HANDLE result;
	GetProperty(DISPID_HWND, VT_I4, (void*)&result);
	return result;
}

void CDatatbl::SetHWnd(OLE_HANDLE propVal)
{
	SetProperty(DISPID_HWND, VT_I4, propVal);
}

long CDatatbl::GetDropDownType()
{
	long result;
	GetProperty(0xb, VT_I4, (void*)&result);
	return result;
}

void CDatatbl::SetDropDownType(long propVal)
{
	SetProperty(0xb, VT_I4, propVal);
}

long CDatatbl::GetVirtualMemType()
{
	long result;
	GetProperty(0xc, VT_I4, (void*)&result);
	return result;
}

void CDatatbl::SetVirtualMemType(long propVal)
{
	SetProperty(0xc, VT_I4, propVal);
}

BOOL CDatatbl::GetDroppedState()
{
	BOOL result;
	GetProperty(0x12, VT_BOOL, (void*)&result);
	return result;
}

void CDatatbl::SetDroppedState(BOOL propVal)
{
	SetProperty(0x12, VT_BOOL, propVal);
}

CDTCurCell CDatatbl::GetCurCell()
{
	LPDISPATCH pDispatch;
	GetProperty(0x13, VT_DISPATCH, (void*)&pDispatch);
	return CDTCurCell(pDispatch);
}

void CDatatbl::SetCurCell(LPDISPATCH propVal)
{
	SetProperty(0x13, VT_DISPATCH, propVal);
}

CDTRowSet CDatatbl::GetRowSet()
{
	LPDISPATCH pDispatch;
	GetProperty(0x14, VT_DISPATCH, (void*)&pDispatch);
	return CDTRowSet(pDispatch);
}

void CDatatbl::SetRowSet(LPDISPATCH propVal)
{
	SetProperty(0x14, VT_DISPATCH, propVal);
}

CDTColumnSet CDatatbl::GetColumnSet()
{
	LPDISPATCH pDispatch;
	GetProperty(0x15, VT_DISPATCH, (void*)&pDispatch);
	return CDTColumnSet(pDispatch);
}

void CDatatbl::SetColumnSet(LPDISPATCH propVal)
{
	SetProperty(0x15, VT_DISPATCH, propVal);
}

CDTCellSet CDatatbl::GetCellSet()
{
	LPDISPATCH pDispatch;
	GetProperty(0x16, VT_DISPATCH, (void*)&pDispatch);
	return CDTCellSet(pDispatch);
}

void CDatatbl::SetCellSet(LPDISPATCH propVal)
{
	SetProperty(0x16, VT_DISPATCH, propVal);
}

long CDatatbl::GetVMDataKey()
{
	long result;
	GetProperty(0x17, VT_I4, (void*)&result);
	return result;
}

void CDatatbl::SetVMDataKey(long propVal)
{
	SetProperty(0x17, VT_I4, propVal);
}

float CDatatbl::GetLeftPaneWidth()
{
	float result;
	GetProperty(0x18, VT_R4, (void*)&result);
	return result;
}

void CDatatbl::SetLeftPaneWidth(float propVal)
{
	SetProperty(0x18, VT_R4, propVal);
}

float CDatatbl::GetTopPaneHeight()
{
	float result;
	GetProperty(0x19, VT_R4, (void*)&result);
	return result;
}

void CDatatbl::SetTopPaneHeight(float propVal)
{
	SetProperty(0x19, VT_R4, propVal);
}

BOOL CDatatbl::GetRedraw()
{
	BOOL result;
	GetProperty(0xd, VT_BOOL, (void*)&result);
	return result;
}

void CDatatbl::SetRedraw(BOOL propVal)
{
	SetProperty(0xd, VT_BOOL, propVal);
}

LPUNKNOWN CDatatbl::GetDataSource()
{
	LPUNKNOWN result;
	GetProperty(0x1a, VT_UNKNOWN, (void*)&result);
	return result;
}

void CDatatbl::SetDataSource(LPUNKNOWN propVal)
{
	SetProperty(0x1a, VT_UNKNOWN, propVal);
}

long CDatatbl::GetBorderStyle()
{
	long result;
	GetProperty(0xe, VT_I4, (void*)&result);
	return result;
}

void CDatatbl::SetBorderStyle(long propVal)
{
	SetProperty(0xe, VT_I4, propVal);
}

long CDatatbl::GetAppearance()
{
	long result;
	GetProperty(0xf, VT_I4, (void*)&result);
	return result;
}

void CDatatbl::SetAppearance(long propVal)
{
	SetProperty(0xf, VT_I4, propVal);
}

long CDatatbl::GetMousePointer()
{
	long result;
	GetProperty(0x10, VT_I4, (void*)&result);
	return result;
}

void CDatatbl::SetMousePointer(long propVal)
{
	SetProperty(0x10, VT_I4, propVal);
}

BOOL CDatatbl::GetLargeData()
{
	BOOL result;
	GetProperty(0x11, VT_BOOL, (void*)&result);
	return result;
}

void CDatatbl::SetLargeData(BOOL propVal)
{
	SetProperty(0x11, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CDatatbl operations

void CDatatbl::Reset()
{
	InvokeHelper(0x1b, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CDatatbl::VMReady(long NumRows)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 NumRows);
}

void CDatatbl::DBAutoConfig()
{
	InvokeHelper(0x1d, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CDatatbl::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
