#ifndef __DATATBL_H__
#define __DATATBL_H__

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;
class CDTCurCell;
class CDTRowSet;
class CDTColumnSet;
class CDTCellSet;

/////////////////////////////////////////////////////////////////////////////
// CDatatbl wrapper class

class CDatatbl : public CWnd
{
protected:
	DECLARE_DYNCREATE(CDatatbl)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x4c1df000, 0xd3ff, 0x11ce, { 0x84, 0xba, 0x48, 0x4f, 0x4d, 0xf9, 0x14, 0xe6 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	unsigned long GetGridLineColor();
	void SetGridLineColor(unsigned long);
	BOOL GetAllowPaintCellEvent();
	void SetAllowPaintCellEvent(BOOL);
	BOOL GetVertGridLines();
	void SetVertGridLines(BOOL);
	long GetVertScrollBar();
	void SetVertScrollBar(long);
	BOOL GetVertSplitPane();
	void SetVertSplitPane(BOOL);
	BOOL GetHorzSplitPane();
	void SetHorzSplitPane(BOOL);
	unsigned long GetSelBackColor();
	void SetSelBackColor(unsigned long);
	long GetHorzScrollBar();
	void SetHorzScrollBar(long);
	BOOL GetHorzGridLines();
	void SetHorzGridLines(BOOL);
	unsigned long GetSelForeColor();
	void SetSelForeColor(unsigned long);
	OLE_COLOR GetBackColor();
	void SetBackColor(OLE_COLOR);
	BOOL GetEnabled();
	void SetEnabled(BOOL);
	COleFont GetFont();
	void SetFont(LPDISPATCH);
	OLE_COLOR GetForeColor();
	void SetForeColor(OLE_COLOR);
	OLE_HANDLE GetHWnd();
	void SetHWnd(OLE_HANDLE);
	long GetDropDownType();
	void SetDropDownType(long);
	long GetVirtualMemType();
	void SetVirtualMemType(long);
	BOOL GetDroppedState();
	void SetDroppedState(BOOL);
	CDTCurCell GetCurCell();
	void SetCurCell(LPDISPATCH);
	CDTRowSet GetRowSet();
	void SetRowSet(LPDISPATCH);
	CDTColumnSet GetColumnSet();
	void SetColumnSet(LPDISPATCH);
	CDTCellSet GetCellSet();
	void SetCellSet(LPDISPATCH);
	long GetVMDataKey();
	void SetVMDataKey(long);
	float GetLeftPaneWidth();
	void SetLeftPaneWidth(float);
	float GetTopPaneHeight();
	void SetTopPaneHeight(float);
	BOOL GetRedraw();
	void SetRedraw(BOOL);
	LPUNKNOWN GetDataSource();
	void SetDataSource(LPUNKNOWN);
	long GetBorderStyle();
	void SetBorderStyle(long);
	long GetAppearance();
	void SetAppearance(long);
	long GetMousePointer();
	void SetMousePointer(long);
	BOOL GetLargeData();
	void SetLargeData(BOOL);

// Operations
public:
	void Reset();
	void VMReady(long NumRows);
	void DBAutoConfig();
	void AboutBox();
};

#endif // __DATATBL_H__
