// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "dtcell.h"

// Dispatch interfaces referenced by this interface
#include "Font.h"


/////////////////////////////////////////////////////////////////////////////
// CDTCell properties

COleFont CDTCell::GetFont()
{
	LPDISPATCH pDispatch;
	GetProperty(0x1, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CDTCell::SetFont(LPDISPATCH propVal)
{
	SetProperty(0x1, VT_DISPATCH, propVal);
}

unsigned long CDTCell::GetBackColor()
{
	unsigned long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CDTCell::SetBackColor(unsigned long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

unsigned long CDTCell::GetForeColor()
{
	unsigned long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CDTCell::SetForeColor(unsigned long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

unsigned long CDTCell::GetSelBackColor()
{
	unsigned long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CDTCell::SetSelBackColor(unsigned long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

unsigned long CDTCell::GetSelForeColor()
{
	unsigned long result;
	GetProperty(0x5, VT_I4, (void*)&result);
	return result;
}

void CDTCell::SetSelForeColor(unsigned long propVal)
{
	SetProperty(0x5, VT_I4, propVal);
}

BOOL CDTCell::GetNullFlag()
{
	BOOL result;
	GetProperty(0x6, VT_BOOL, (void*)&result);
	return result;
}

void CDTCell::SetNullFlag(BOOL propVal)
{
	SetProperty(0x6, VT_BOOL, propVal);
}

VARIANT CDTCell::GetValue()
{
	VARIANT result;
	GetProperty(0x7, VT_VARIANT, (void*)&result);
	return result;
}

void CDTCell::SetValue(const VARIANT& propVal)
{
	SetProperty(0x7, VT_VARIANT, &propVal);
}

BOOL CDTCell::GetSelected()
{
	BOOL result;
	GetProperty(0x8, VT_BOOL, (void*)&result);
	return result;
}

void CDTCell::SetSelected(BOOL propVal)
{
	SetProperty(0x8, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CDTCell operations

void CDTCell::Invalidate()
{
	InvokeHelper(0x9, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CDTCell::MakeVisible()
{
	InvokeHelper(0xa, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

BOOL CDTCell::GetRect(long Pane, float* Left, float* Top, float* Right, float* Bottom)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4 VTS_PR4 VTS_PR4 VTS_PR4 VTS_PR4;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Pane, Left, Top, Right, Bottom);
	return result;
}
