#ifndef __DTCOLUMN_H__
#define __DTCOLUMN_H__

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CDTColumn wrapper class

class CDTColumn : public COleDispatchDriver
{
public:
	CDTColumn() {}		// Calls COleDispatchDriver default constructor
	CDTColumn(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDTColumn(const CDTColumn& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	unsigned long GetBackColor();
	void SetBackColor(unsigned long);
	unsigned long GetForeColor();
	void SetForeColor(unsigned long);
	unsigned long GetSelBackColor();
	void SetSelBackColor(unsigned long);
	unsigned long GetSelForeColor();
	void SetSelForeColor(unsigned long);
	COleFont GetFont();
	void SetFont(LPDISPATCH);
	long GetDataType();
	void SetDataType(long);
	short GetDataLen();
	void SetDataLen(short);
	long GetExtra1();
	void SetExtra1(long);
	long GetExtra2();
	void SetExtra2(long);
	CString GetFormat();
	void SetFormat(LPCTSTR);
	CString GetHeading();
	void SetHeading(LPCTSTR);
	CString GetList();
	void SetList(LPCTSTR);
	long GetDataEdit();
	void SetDataEdit(long);
	CString GetDefVal();
	void SetDefVal(LPCTSTR);
	BOOL GetHidden();
	void SetHidden(BOOL);
	BOOL GetLocked();
	void SetLocked(BOOL);
	CString GetName();
	void SetName(LPCTSTR);
	BOOL GetOverwrite();
	void SetOverwrite(BOOL);
	VARIANT GetValue();
	void SetValue(const VARIANT&);
	long GetHeadAlign();
	void SetHeadAlign(long);
	long GetDataAlign();
	void SetDataAlign(long);
	long GetResize();
	void SetResize(long);
	float GetWidth();
	void SetWidth(float);
	BOOL GetEditAutoHScroll();
	void SetEditAutoHScroll(BOOL);
	BOOL GetEditAutoVScroll();
	void SetEditAutoVScroll(BOOL);
	BOOL GetEditLowercase();
	void SetEditLowercase(BOOL);
	BOOL GetEditUppercase();
	void SetEditUppercase(BOOL);
	BOOL GetEditMultiLine();
	void SetEditMultiLine(BOOL);
	BOOL GetEditWantReturn();
	void SetEditWantReturn(BOOL);
	BOOL GetSelected();
	void SetSelected(BOOL);
	BOOL GetBound();
	void SetBound(BOOL);

// Operations
public:
	void Invalidate();
	VARIANT Total();
	long Search(const VARIANT& Value, long After);
};

#endif // __DTCOLUMN_H__
