#ifndef __DTCOLUMNSET_H__
#define __DTCOLUMNSET_H__

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CDTColumn;

/////////////////////////////////////////////////////////////////////////////
// CDTColumnSet wrapper class

class CDTColumnSet : public COleDispatchDriver
{
public:
	CDTColumnSet() {}		// Calls COleDispatchDriver default constructor
	CDTColumnSet(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDTColumnSet(const CDTColumnSet& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetCount();
	void SetCount(long);
	BOOL GetAllowResize();
	void SetAllowResize(BOOL);
	long GetSelectType();
	void SetSelectType(long);
	short GetNumListItems();
	void SetNumListItems(short);
	BOOL GetHideListArrow();
	void SetHideListArrow(BOOL);
	short GetLabelType();
	void SetLabelType(short);
	BOOL GetSortEnabled();
	void SetSortEnabled(BOOL);

// Operations
public:
	void Remove(long Index);
	void Move(long Source, long Dest);
	void Copy(long Source, long Dest);
	long GetSelectCount();
	void SelectRange(long Start, long End, BOOL SelectOn);
	long GetVisCount(long LRPane);
	long GetSortKey(long Index);
	void SetSortKey(long Index, long nNewValue);
	BOOL GetSortAsc(long Index);
	void SetSortAsc(long Index, BOOL bNewValue);
	BOOL GetSortCaseI(long Index);
	void SetSortCaseI(long Index, BOOL bNewValue);
	long GetFirstVisible(long LRPane);
	void SetFirstVisible(long LRPane, long nNewValue);
	void Add(long Index);
	long GetColWithName(LPCTSTR Name);
	CDTColumn GetItem(long Index);
	void SetItem(long Index, LPDISPATCH newValue);
	CDTColumn Get_Item(long Index);
	void Set_Item(long Index, LPDISPATCH newValue);
	long GetSelect(long After);
};

#endif // __DTCOLUMNSET_H__
