#ifndef __DTCURCELL_H__
#define __DTCURCELL_H__

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CDTCurCell wrapper class

class CDTCurCell : public COleDispatchDriver
{
public:
	CDTCurCell() {}		// Calls COleDispatchDriver default constructor
	CDTCurCell(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDTCurCell(const CDTCurCell& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetColumn();
	void SetColumn(long);
	long GetRow();
	void SetRow(long);
	long GetPane();
	void SetPane(long);
	COleFont GetFont();
	void SetFont(LPDISPATCH);
	VARIANT GetEditValue();
	void SetEditValue(const VARIANT&);
	unsigned long GetBackColor();
	void SetBackColor(unsigned long);
	unsigned long GetForeColor();
	void SetForeColor(unsigned long);
	unsigned long GetSelBackColor();
	void SetSelBackColor(unsigned long);
	unsigned long GetSelForeColor();
	void SetSelForeColor(unsigned long);
	unsigned long GetFocusPenColor();
	void SetFocusPenColor(unsigned long);
	short GetFocusPenWidth();
	void SetFocusPenWidth(short);
	short GetFocusPenStyle();
	void SetFocusPenStyle(short);
	short GetKeyForAbortEdit();
	void SetKeyForAbortEdit(short);
	short GetKeyForBeginEdit();
	void SetKeyForBeginEdit(short);
	short GetKeyForEndEdit();
	void SetKeyForEndEdit(short);
	BOOL GetEndEditTab();
	void SetEndEditTab(BOOL);
	BOOL GetEndEditCtrlTab();
	void SetEndEditCtrlTab(BOOL);
	BOOL GetEndEditLfRtArrows();
	void SetEndEditLfRtArrows(BOOL);
	BOOL GetEndEditUpDnArrows();
	void SetEndEditUpDnArrows(BOOL);
	BOOL GetEndEditClick();
	void SetEndEditClick(BOOL);
	VARIANT GetValue();
	void SetValue(const VARIANT&);
	BOOL GetAllowCellEdit();
	void SetAllowCellEdit(BOOL);
	BOOL GetTabToNextCell();
	void SetTabToNextCell(BOOL);
	BOOL GetMoveColMajor();
	void SetMoveColMajor(BOOL);
	long GetHWndListBox();
	void SetHWndListBox(long);
	long GetHWndEditBox();
	void SetHWndEditBox(long);
	long GetSelStart();
	void SetSelStart(long);
	long GetSelLength();
	void SetSelLength(long);

// Operations
public:
	void MoveToNext();
	void MoveToPrev();
	void BeginEdit();
	void EndEdit();
	void AbortEdit();
};

#endif // __DTCURCELL_H__
