// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "dtrow.h"

// Dispatch interfaces referenced by this interface
#include "font.h"


/////////////////////////////////////////////////////////////////////////////
// CDTRow properties

unsigned long CDTRow::GetBackColor()
{
	unsigned long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CDTRow::SetBackColor(unsigned long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

unsigned long CDTRow::GetSelBackColor()
{
	unsigned long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CDTRow::SetSelBackColor(unsigned long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

unsigned long CDTRow::GetForeColor()
{
	unsigned long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CDTRow::SetForeColor(unsigned long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

unsigned long CDTRow::GetSelForeColor()
{
	unsigned long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CDTRow::SetSelForeColor(unsigned long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

COleFont CDTRow::GetFont()
{
	LPDISPATCH pDispatch;
	GetProperty(0x5, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CDTRow::SetFont(LPDISPATCH propVal)
{
	SetProperty(0x5, VT_DISPATCH, propVal);
}

CString CDTRow::GetLabel()
{
	CString result;
	GetProperty(0x6, VT_BSTR, (void*)&result);
	return result;
}

void CDTRow::SetLabel(LPCTSTR propVal)
{
	SetProperty(0x6, VT_BSTR, propVal);
}

VARIANT CDTRow::GetValue()
{
	VARIANT result;
	GetProperty(0x7, VT_VARIANT, (void*)&result);
	return result;
}

void CDTRow::SetValue(const VARIANT& propVal)
{
	SetProperty(0x7, VT_VARIANT, &propVal);
}

BOOL CDTRow::GetSelected()
{
	BOOL result;
	GetProperty(0x8, VT_BOOL, (void*)&result);
	return result;
}

void CDTRow::SetSelected(BOOL propVal)
{
	SetProperty(0x8, VT_BOOL, propVal);
}

long CDTRow::GetResize()
{
	long result;
	GetProperty(0x9, VT_I4, (void*)&result);
	return result;
}

void CDTRow::SetResize(long propVal)
{
	SetProperty(0x9, VT_I4, propVal);
}

float CDTRow::GetHeight()
{
	float result;
	GetProperty(0xa, VT_R4, (void*)&result);
	return result;
}

void CDTRow::SetHeight(float propVal)
{
	SetProperty(0xa, VT_R4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CDTRow operations

void CDTRow::Invalidate()
{
	InvokeHelper(0xb, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
