//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by FOTOBROW.rc
//
#define ID_COLOR                        0
#define ID_PROPERTIES                   1
#define ID_IMPORT_DATA                  3
#define IDC_CALCULATE                   3
#define ID_MAKE_IDENTITY                4
#define IDC_SURVEY_XFORM                5
#define ID_UNLINK                       6
#define IDC_APPLY                       7
#define IDC_ADD                         8
#define IDC_REMOVE                      9
#define ID_OPEN_IMAGE                   10
#define IDD_ABOUTBOX                    100
#define IDD_3DPOINTTABLE                101
#define IDD_3DCYLINDERTABLE             102
#define IDD_3DCIRCLETABLE               103
#define IDD_3DTARGETTABLE               104
#define IDD_3DCAMERATABLE               105
#define IDC_SELECT                      110
#define IDC_MEASURE                     111
#define IDC_CAMERA                      112
#define IDC_IMAGE                       113
#define IDC_TARGET                      114
#define ID_ACCEL_SCROLLDOWN             115
#define ID_ACCEL_SCROLLUP               116
#define ID_ACCEL_SCROLLRIGHT            117
#define ID_ACCEL_SCROLLLEFT             118
#define ID_ACCEL_SCROLLPAGEDOWN         119
#define ID_ACCEL_SCROLLPAGEUP           120
#define ID_ACCEL_SCROLLPAGERIGHT        121
#define ID_ACCEL_SCROLLPAGELEFT         122
#define ID_ACCEL_FITTOVIEW              123
#define IDR_MAINFRAME                   124
#define IDC_ORTHO                       125
#define IDC_PERSPECTIVE                 126
#define IDC_CENTER                      127
#define IDR_BITMAPTYPE                  129
#define IDC_ZOOMIN                      131
#define IDC_ZOOMOUT                     132
#define IDR_IMAGETOOLS                  134
#define IDR_MONO_EDITBARHORZ            136
#define IDR_GRAPHICS                    137
#define IDR_COLUMNGRID                  138
#define IDR_COLOR_EDITBARHORZ           141
#define IDR_MONO_EDITBARVERT            142
#define IDB_BACKGROUND                  143
#define IDD_RESULTS                     145
#define IDC_OVERLAY                     145
#define IDD_GENERAL                     146
#define IDC_RAYS                        146
#define IDD_3POINTS                     147
#define ID_INDICATOR_OVRL               147
#define ID_INDICATOR_RAYS               148
#define IDD_3DPOINTS                    149
#define ID_KILL_CREATE_CYLINDER         149
#define IDR_ZONEGRID2                   150
#define IDD_SETTINGS                    152
#define IDD_ZONEINPUT                   156
#define IDD_COLUMNGRID                  159
#define IDD_IMAGES                      163
#define IDR_VIEWS                       165
#define IDR_MEASURE                     166
#define IDD_SELECT_ZONE                 167
#define IDD_COORD_XFORM                 168
#define IDD_ENGINEERING                 169
#define IDD_CONSTRUCTION                170
#define IDD_MAINTANANCE                 171
#define IDD_COMMISIONING                172
#define IDD_PICKEQUIP                   173
#define IDD_SELECT_EQUIP                175
#define IDB_EQUIPMENT                   177
#define IDB_IMAGE                       178
#define IDD_PROJECT_SETTINGS            179
#define IDB_ABD_BIG                     183
#define IDB_ABD_MED                     184
#define IDB_ABD_SMALL                   185
#define IDB_PM3_LOGO                    186
#define IDB_PM3_SYMBOL                  187
#define IDD_DRAWLIST                    188
#define IDB_CYLINDER                    189
#define IDB_CONE                        190
#define IDB_BOX                         191
#define IDB_NODE                        192
#define IDB_EYE_OPEN                    196
#define IDB_EYE_CLOSED                  197
#define IDD_PDMS_TRANSFORM              199
#define IDP_OLE_INIT_FAILED             200
#define ID_ACCEL_COPYGRID               201
#define IDR_COLOR_EDITBARVERT           202
#define IDD_OPEN_PROJECTS               203
#define IDC_CROSSHAIR                   204
#define IDB_PM3_LOGO_old                205
#define IDD_LIGHT_ADJUST                206
#define IDB_PM3_BACKGROUND              207
#define IDD_OPENGL_SETTINGS             207
#define IDB_SPLASH                      208
#define IDD_CYLINDERBYEDGE              209
#define IDB_ANNOY_BACKGROUND            210
#define IDD_CYLINDER                    211
#define IDD_CIRCLE_BY_EDGE              213
#define IDD_CIRCLE_BY_3DPOINT           214
#define IDD_ELEMENT_LIST_VIEW           215
#define IDR_ELEMENTLIST                 216
#define IDR_MEMBER_LIST_POP_MENU        219
#define IDD_CIRCLE                      220
#define IDD_RADIOGRAPHY                 229
#define IDB_OGL_GREEN                   230
#define IDB_OGL_RED                     231
#define IDB_OGL_YELLOW                  232
#define IDB_OGL_BLUE                    233
#define IDB_OGL_GREY                    234
#define IDB_OGL_PURPLE                  235
#define IDB_OGL_CYAN                    236
#define IDB_OGL_LT_BLUE                 237
#define IDB_OGL_LT_RED                  238
#define IDB_OGL_LT_GREEN                239
#define IDB_OGL_LT_CYAN                 240
#define IDB_OGL_LT_MAGENTA              241
#define IDB_OGL_LT_YELLOW               242
#define IDB_OGL_LT_WHITE                243
#define IDB_OGL_BLACK                   244
#define IDI_SMALL_MAINFRAME             245
#define IDD_BUNDLE_CALC                 247
#define IDD_3DPOINTGRIDBAR              252
#define IDD_COLUMNEDITOR                254
#define IDD_ZONEEDITOR                  256
#define IDD_QUICKCYLINDER               259
#define IDB_CYLINDER2                   260
#define IDD_ENDPOINTCYLINDER            261
#define IDD_DIALOG1                     262
#define IDB_SPLASH_ALPHA                263
#define IDD_SAVE_DGN                    264
#define IDC_EDIT1                       1002
#define IDC_EDIT2                       1003
#define IDD_COLUMNTABLE                 1004
#define IDC_DATAFILE                    1004
#define IDD_ZONETABLE                   1005
#define IDC_SPECIALAPP                  1005
#define IDC_IMAGEPATH                   1006
#define IDC_IMAGELIST                   1007
#define IDC_ZONELIST                    1008
#define IDC_POINT1_EAST                 1009
#define IDC_POINT2_EAST                 1010
#define IDC_POINT1_NORTH                1011
#define IDC_POINT2_NORTH                1012
#define IDC_RADIO1                      1013
#define IDC_RADIO2                      1014
#define IDC_RADIO3                      1015
#define IDC_RADIO4                      1016
#define IDC_CALC_EAST                   1017
#define IDC_RADIO5                      1017
#define IDC_CALC_NORTH                  1018
#define IDC_RADIO6                      1018
#define IDC_CALC_UP                     1019
#define IDC_RADIO7                      1019
#define IDC_REAL_EAST                   1020
#define IDC_RADIO8                      1020
#define IDC_REAL_NORTH                  1021
#define IDC_REAL_UP                     1022
#define IDC_FLUSH_SCH_DATE3             1023
#define IDC_TURN_SCH_DATE3              1024
#define IDC_INSPECTION_DATE             1025
#define IDC_MAINT_SCH                   1026
#define IDC_PARTS_INV                   1027
#define IDC_ISOLATION_LIST              1028
#define IDC_BY_EQUIPMENT                1029
#define IDC_BY_PROCEDURE                1030
#define IDC_TYPE_FILTER                 1031
#define IDC_AREA_FILTER                 1032
#define IDC_NAME_FILTER                 1033
#define IDC_DATE_FILTER                 1034
#define IDC_DATE                        1035
#define IDC_EQ_LIST                     1036
#define IDC_PROJLIST                    1038
#define IDC_PROJECTNAME                 1039
#define IDC_DATABASE_PATH               1041
#define IDC_IMAGE_REDUCE_FACTOR         1042
#define IDC_MEMBERLIST                  1043
#define IDC_DRAWLIST                    1044
#define IDC_DRAWSTYLE                   1047
#define IDC_MATRIX_ELEMENT0             1048
#define IDC_USER1                       1049
#define IDC_MATRIX_ELEMENT2             1050
#define IDC_LIGHT_RED                   1050
#define IDC_MATRIX_ELEMENT3             1051
#define IDC_LIGHT_GREEN                 1051
#define IDC_MATRIX_ELEMENT4             1052
#define IDC_LIGHT_BLUE                  1052
#define IDC_MATRIX_ELEMENT5             1053
#define IDC_LIGHT_ALPHA                 1053
#define IDC_MATRIX_ELEMENT6             1054
#define IDC_VALUE_RED                   1054
#define IDC_MATRIX_ELEMENT7             1055
#define IDC_VALUE_GREEN                 1055
#define IDC_MATRIX_ELEMENT8             1056
#define IDC_VALUE_BLUE                  1056
#define IDC_MATRIX_ELEMENT9             1057
#define IDC_VALUE_ALPHA                 1057
#define IDC_MATRIX_ELEMENT10            1058
#define IDC_SYNCH_RGB                   1058
#define IDC_MATRIX_ELEMENT11            1059
#define IDC_ALPHA_TEST                  1059
#define IDC_AUTO_NORMAL                 1060
#define IDC_BLEND                       1061
#define IDC_COLOR_MATERIAL              1062
#define IDC_CULL_FACE                   1063
#define IDC_DEPTH_TEST                  1064
#define IDC_DITHER                      1065
#define IDC_FOG                         1066
#define IDC_LIGHTING                    1067
#define IDC_LINE_SMOOTH                 1068
#define IDC_LINE_STIPPLE                1069
#define IDC_LOGIC_OP                    1070
#define IDC_NORMALIZE                   1071
#define IDC_POINT_SMOOTH                1072
#define IDC_POLYGON_SMOOTH              1073
#define IDC_POLYGON_STIPPLE             1074
#define IDC_SCISSOR_TEST                1075
#define IDC_STENCIL_TEST                1076
#define IDC_TEXTURE_1D                  1077
#define IDC_TEXTURE_2D                  1078
#define IDC_NEXT                        1084
#define IDC_BACK                        1085
#define IDC_LABEL                       1086
#define IDC_DATABASE_TREE               1088
#define IDC_RADIUS                      1090
#define IDC_HEIGHT                      1091
#define IDC_START_EAST                  1092
#define IDC_NUMBER_OF_POINTS            1092
#define IDC_SPREADSHEET_TAGS            1093
#define IDC_START_NORTH                 1094
#define IDC_ELEMENT_LIST                1094
#define IDC_START_HEIGHT                1095
#define IDC_EQUIP_TAG_DATA              1095
#define IDC_END_EAST                    1096
#define IDC_BROWSE_DATAFILE             1096
#define IDC_END_NORTH                   1097
#define IDC_BROWSE_APP                  1097
#define IDC_END_HEIGHT                  1098
#define IDC_UNITS                       1100
#define IDC_NAME                        1101
#define IDC_VIEWFILE                    1101
#define IDC_ASSIGN_EQUIP                1102
#define IDC_SCANTAG                     1102
#define IDC_SYSTEMLIST                  1103
#define IDC_RADIOGRAPHY_DATA            1103
#define IDC_UNITS2                      1104
#define IDC_EQUIPMENT                   1104
#define IDC_FLUSH_SCH_DATE              1105
#define IDC_BUNDLE_LIST                 1105
#define IDC_TURN_SCH_DATE               1106
#define IDC_FLUSH_SCH_DATE2             1107
#define IDC_FULL_BUNDLE                 1107
#define IDC_AREA                        1108
#define IDC_INCREMENTAL_BUNDLE          1108
#define IDC_DATATBLCTRL1                1108
#define IDC_3DPOINTGRID                 1108
#define IDC_COLUMNGRID                  1108
#define IDC_ZONEGRID                    1108
#define IDC_TURN_SCH_DATE2              1109
#define IDC_CYLINDER_GRID               1109
#define IDC_EQ_NAME                     1110
#define IDC_BOX_GRID                    1110
#define IDC_EQ_DESCRIPTION              1111
#define IDC_NODE_GRID                   1111
#define IDC_PROJECT_LIST                1112
#define IDC_DUE_DATE                    1112
#define IDC_POINT_GRID                  1112
#define IDC_POINT1                      1112
#define IDC_POINT2                      1113
#define IDC_POINT3                      1114
#define IDC_COLOR                       1115
#define IDC_POINT4                      1115
#define IDC_MATRIX_ELEMENT1             1116
#define IDC_ACCEPT_POINT                1116
#define IDC_POINT1_TEXT                 1117
#define IDC_POINT2_TEXT                 1118
#define IDC_POINT3_TEXT                 1119
#define IDC_POINT4_TEXT                 1120
#define IDC_EDIT3                       1121
#define IDC_EDIT4                       1122
#define IDC_EDIT6                       1124
#define IDC_EDIT7                       1125
#define IDC_BUTTON2                     1127
#define IDC_BUTTON3                     1128
#define IDC_COMBO1                      1130
#define IDC_SCALE                       32777
#define IDC_ZOOM                        32778
#define ID_VIEW_GRAPHIC                 32779
#define ID_SETTINGS_OPTIONS             32780
#define ID_EDIT_ZONES                   32781
#define ID_EDIT_COLUMNS                 32782
#define ID_EDIT_IMAGES                  32784
#define ID_SET_ORTHO                    32785
#define ID_SET_PERSPECTIVE              32786
#define IDC_CLIPVOLUME                  32791
#define ID_EDIT_TRANSFORMATIONS         32792
#define ID_VIEW_DEFINEREGION            32793
#define ID_VIEW_DELETEREGION            32794
#define ID_VIEW_LABELREGION             32795
#define ID_EDIT_EQUIPDATA               32796
#define ID_EDIT_EQUIPIMAGES             32797
#define ID_FILE_PROJECTS                32798
#define ID_GRAPHICS_DRAWLIST            32802
#define ID_VIEW_FILLMODE                32803
#define ID_GRAPHICS_CLIPZONES           32811
#define ID_DELETE_COLUMN                32813
#define ID_DELETE_ZONE                  32814
#define ID_GRAPHICS_LIGHT               32815
#define ID_GRAPHICS_FITVIEW             32816
#define ID_GRAPHICS_OPENGLSETTINGS      32817
#define ID_MEASURE_CYLINDERBYEDGE       32818
#define ID_MEASURE_CIRCLEBYEDGE         32819
#define ID_MEASURE_CIRCLEBY3DPOINT      32820
#define ID_VIEW_ELEMENTLIST             32821
#define ID_BUTTON32839                  32839
#define ID_BUTTON32840                  32840
#define ID_BUTTON32844                  32844
#define ID_VIEW_LABLEREGION             32853
#define ID_BUTTON32857                  32857
#define ID_BUTTON32858                  32858
#define ID_BUTTON32859                  32859
#define ID_VISIBLE                      32862
#define ID_MEMBERLIST_COLOR             32865
#define ID_MEMBERLIST_PROPERTIES        32866
#define ID_MEMBERLIST_VISIBLE_WIREFRAME 32867
#define ID_MEMBERLIST_VISIBLE_SOLID     32868
#define ID_MEMBERLIST_VISIBLE_INVISIBLE 32869
#define ID_MEMBERLIST_COLOR_BLACK       32870
#define ID_MEMBERLIST_COLOR_BLUE        32871
#define ID_MEMBERLIST_COLOR_RED         32872
#define ID_MEMBERLIST_COLOR_GREEN       32873
#define ID_MEMBERLIST_COLOR_YELLOW      32874
#define ID_MEMBERLIST_COLOR_MAGENTA     32875
#define ID_MEMBERLIST_COLOR_CYAN        32876
#define ID_MEMBERLIST_COLOR_WHITE       32877
#define ID_MEMBERLIST_COLOR_LIGHTBLUE   32878
#define ID_MEMBERLIST_COLOR_LIGHTGREEN  32879
#define ID_MEMBERLIST_COLOR_LIGHTRED    32880
#define ID_MEMBERLIST_COLOR_LIGHTYELLOW 32881
#define ID_MEMBERLIST_COLOR_LIGHTMAGENTA 32882
#define ID_MEMBERLIST_COLOR_LIGHTCYAN   32883
#define ID_MEMBERLIST_COLOR_GREY        32884
#define ID_MEMBERLIST_COLOR_TEMP        32885
#define ID_EDIT_BUNDLECALCULATIONS      32888
#define ID_MEMBERLIST_SETASREFERENCENODE 32890
#define ID_MEMBERLIST_CUT               32891
#define ID_MEMBERLIST_COPY              32892
#define ID_MEMBERLIST_PASTE             32893
#define ID_MEMBERLIST_DELETE            32894
#define ID_FILE_IMPORT_SURVEYDATA       32895
#define ID_FILE_IMPORT_REVIEWMODEL      32896
#define ID_MEMBERLIST_CALC_CIRC_3DPOINTS 32898
#define ID_MEASURE_QUICKCYLINDER        32900
#define ID_MEASURE_CYLINDERBYENDPOINTS  32901
#define ID_FILE_SAVE_WORK               32903
#define ID_FILE_GET_WORK                32904
#define ID_MEMBERLIST_SAVEDGN           32905
#define ID_OGL_BLACK                    33000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        266
#define _APS_NEXT_COMMAND_VALUE         32906
#define _APS_NEXT_CONTROL_VALUE         1131
#define _APS_NEXT_SYMED_VALUE           154
#endif
#endif
